server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ev_platform
    username: postgres
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update

  security:
    user:
      name: admin
      password: admin
